repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/mtkennerly/pre-commit-hooks
    rev: v0.3.0
    hooks:
      - id: poetry-black
      - id: poetry-mypy
      - id: poetry-ruff
